### ISSUE TITLE
Cypress peer-dependency v10.*

### ISSUE THREAD

**Issue by chikamichi** [deepsquare-io/cypress-iframe#1]
Hi :)

Cypress just released v10 and 10.0.1 today. Would you consider relaxing the peer-dependency? for instance:

``` sh
"peerDependencies": {
  "cypress": "^9.2.0 || ^10.0.0"
},
```

Note: I haven’t tested cypress-iframe locally against cypress v10.*

**Comment by matbour** [comment]
I just updated the manifest, but this has not been tested by the team. Use Cypress 10 at your own risk!

**Comment by chikamichi** [comment]
Thank you! Merci!
